name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: List contents of target directory (debugging)
        run: ls -l target

      - name: Rename JAR File
        run: |
          JAR_NAME=$(ls target/*.jar)
          echo "Renaming $JAR_NAME to my-project.jar"
          mv $JAR_NAME target/my-project.jar

      - name: List contents of target directory after renaming (debugging)
        run: ls -l target

      - name: Create JAR directory
        run: mkdir -p docs/jar

      - name: List contents of docs/jar directory (debugging)
        run: ls -l docs/jar

      - name: Move JAR to docs directory
        run: mv target/my-project.jar docs/jar/

      - name: List contents of docs/jar directory after moving JAR (debugging)
        run: ls -l docs/jar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_GHTOKEN }}
          publish_dir: ./docs
